CREATE DATABASE IF NOT EXISTS PROGRAMS;

CREATE TABLE IF NOT EXISTS STUDENT(
NAME CHAR(20) NOT NULL,
STUDENTID VARCHAR(20),
EMAIL VARCHAR(50),
PHONE INT(10),
PRIMARY KEY(STUDENTID)
);

CREATE TABLE IF NOT EXISTS INSTRUCTOR(
NAME CHAR(20) NOT NULL,
EMPID VARCHAR(20),
EMAIL VARCHAR(50),
DESIGNATION VARCHAR(20),
PHONE INT(10),
PRIMARY KEY(EMPID)
);

CREATE TABLE IF NOT EXISTS COURSE(
NAME CHAR(20) NOT NULL,
COURSEID VARCHAR(20),
CONTACTHOURS VARCHAR(10),
EMPID VARCHAR(50),
PRIMARY KEY(COURSEID),
FOREIGN KEY(EMPID) REFERENCES INSTRUCTOR(EMPID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAKE(
STUDENTID VARCHAR(20),
COURSEID VARCHAR(20),
GRADE VARCHAR(10),
PRIMARY KEY(STUDENTID,COURSEID),
FOREIGN KEY(STUDENTID) REFERENCES STUDENT(STUDENTID) ON DELETE CASCADE,
FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID) ON DELETE CASCADE
);

INSERT INTO STUDENT (NAME,STUDENTID,EMAIL,PHONE) VALUES ("GOWTHAMI","231058007", "gowthamigbhat0907@gmail.com","876224233");

INSERT INTO INSTRUCTOR (NAME,EMPID,EMAIL,DESIGNATION,PHONE) VALUES ("NIDHI","231058001", "nidhi1234@gmail.com","Teacher","876224222");

INSERT INTO COURSE (NAME,COURSEID,CONTACTHOURS,EMPID) VALUES ("IMAAD","531","5","231058001");

INSERT INTO TAKE (STUDENTID,COURSEID,GRADE) VALUES ("231058007","531","A");


INSERT INTO STUDENT (NAME,STUDENTID,EMAIL,PHONE) VALUES ("AVANI","23105825","avani@gmail.com","944768870");

INSERT INTO INSTRUCTOR (NAME,EMPID,EMAIL,DESIGNATION,PHONE) VALUES ("NAIDILE","213058079","naidile@gmail.com","PRINICIPAL","948017071");

INSERT INTO COURSE (NAME,COURSEID,CONTACTHOURS,EMPID) VALUES ("VIDISHA","511","10","213058079");

INSERT INTO TAKE (STUDENTID,COURSEID,GRADE) VALUES ("23105825","511","B");



CREATE TABLE IF NOT EXISTS NEWCOURSE(
NAME CHAR(20) NOT NULL,
COURSEID VARCHAR(20),
CONTACTHOURS VARCHAR(10),
EMPID VARCHAR(50),
PRIMARY KEY(COURSEID),
FOREIGN KEY(EMPID) REFERENCES INSTRUCTOR(EMPID) ON DELETE CASCADE
);

INSERT INTO NEWCOURSE (NAME,COURSEID,CONTACTHOURS,EMPID)
SELECT * FROM COURSE;


